name: Keep GitHub Active (README)

on:
  schedule:
    - cron: "5 6 * * *"  # her gün 09:05 (TRT, UTC+3) = 06:05 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README "Last update" marker
        run: |
          dt="$(date -u '+%Y-%m-%d %H:%M UTC')"
          sed -i 's|<!--LAST-UPDATE-START-->.*<!--LAST-UPDATE-END-->|<!--LAST-UPDATE-START-->Last update: '"$dt"'<!--LAST-UPDATE-END-->|' README.md

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: daily README update ($dt)" || echo "No changes to commit"
          git push origin HEAD:main
